export const types = {
    GET_EMPLOYEEDATA_REQUEST: "GET_EMPLOYEEDATA_REQUEST",
    GET_EMPLOYEEDATA_SUCCESS: "GET_EMPLOYEEDATA_SUCCESS",
    GET_EMPLOYEEDATA_FAILED: "GET_EMPLOYEEDATA_FAILED",

    GET_EMPLOYEE_ATTENDANCE_REQUEST: "GET_EMPLOYEE_ATTENDANCE_REQUEST",
    GET_EMPLOYEE_ATTENDANCE_SUCCESS: "GET_EMPLOYEE_ATTENDANCE_SUCCESS",
    GET_EMPLOYEE_ATTENDANCE_FAILED: "GET_EMPLOYEE_ATTENDANCE_FAILED",

    GET_EMPLOYEE_LEAVE_WFH_REQUEST: "GET_EMPLOYEE_LEAVE_WFH_REQUEST",
    GET_EMPLOYEE_LEAVE_WFH_SUCCESS: "GET_EMPLOYEE_LEAVE_WFH_SUCCESS",
    GET_EMPLOYEE_LEAVE_WFH_FAILED: "GET_EMPLOYEE_LEAVE_WFH_FAILED",
    





}