export const types = {
  GET_DASHBOARDATA_REQUEST: "GET_DASHBOARDATA_REQUEST",
  GET_DASHBOARDATA_SUCCESS: "GET_DASHBOARDATA_SUCCESS",
  GET_DASHBOARDATA_FAILED: "GET_DASHBOARDATA_FAILED",

  GET_DEMOREQUEST_REQUEST: "GET_DEMOREQUEST_REQUEST",
  GET_DEMOREQUEST_SUCCESS: "GET_DEMOREQUEST_SUCCESS",
  GET_DEMOREQUEST_FAILED: "GET_DEMOREQUEST_FAILED",

  GET_PLANHISTORY_REQUEST: "GET_PLANHISTORY_REQUEST",
  GET_PLANHISTORY_SUCCESS: "GET_PLANHISTORY_SUCCESS",
  GET_PLANHISTORY_FAILED: "GET_PLANHISTORY_FAILED",

  GET_SERVICETYPE_REQUEST: "GET_SERVICETYPE_REQUEST",
  GET_SERVICETYPE_SUCCESS: "GET_SERVICETYPE_SUCCESS",
  GET_SERVICETYPE_FAILED: "GET_SERVICETYPE_FAILED",

  GET_PLANS_REQUEST: "GET_PLANS_REQUEST",
  GET_PLANS_SUCCESS: "GET_PLANS_SUCCESS",
  GET_PLANS_FAILED: "GET_PLANS_FAILED",

  GET_COMPANIES_REQUEST: "GET_COMPANIES_REQUEST",
  GET_COMPANIES_SUCCESS: "GET_COMPANIES_SUCCESS",
  ADD_COMPANIES_SUCCESS: "ADD_COMPANIES_SUCCESS",
  UPDATE_COMPANIES_SUCCESS: "UPDATE_COMPANIES_SUCCESS",
  GET_COMPANIES_FAILED: "GET_COMPANIES_FAILED",

  GET_RECENT_TRANSACTION_REQUEST: "GET_RECENT_TRANSACTION_REQUEST",
  GET_RECENT_TRANSACTION_REQUEST_SUCCESS: "GET_RECENT_TRANSACTION_REQUEST_SUCCESS",
  GET_RECENT_TRANSACTION_REQUEST_FAILED: "GET_RECENT_TRANSACTION_REQUEST_FAILED",

  GET_PENDING_DEMO_REQUEST: "GET_PENDING_DEMO_REQUEST",
  GET_PENDING_DEMO_REQUEST_SUCCESS: "GET_PENDING_DEMO_REQUEST_SUCCESS",
  GET_PENDING_DEMO_REQUEST_FAILED: "GET_PENDING_DEMO_REQUEST_FAILED",

  GET_PURCHASE_SUMMARY_REQUEST: "GET_PURCHASE_SUMMARY_REQUEST",
  GET_PURCHASE_SUMMARY_SUCCESS: "GET_PURCHASE_SUMMARY_SUCCESS",
  GET_PURCHASE_SUMMARY_FAILED: "GET_PURCHASE_SUMMARY_FAILED",





  GET_RECENT_REGISTRATIONS_REQUEST: "GET_RECENT_REGISTRATIONS_REQUEST",
  GET_RECENT_REGISTRATIONS_REQUEST_SUCCESS: "GET_RECENT_REGISTRATIONS_REQUEST_SUCCESS",
  GET_RECENT_REGISTRRATIONS_REQUEST_FAILED: "GET_RECENT_REGISTRRATIONS_REQUEST_FAILED",


  GET_PLAN_EXPIRE_REQUEST: "GET_PLAN_EXPIRE_REQUEST",
  GET_PLAN_EXPIRE_REQUEST_SUCCESS: "GET_PLAN_EXPIRE_REQUEST_SUCCESS",
  GET_PLAN_EXPIRE_REQUEST_FAILED: "GET_PLAN_EXPIRE_REQUEST_FAILED",
  
  


 
};
