export const types = {
    
    GET_DASHBOARDATA_REQUEST : "GET_DASHBOARDATA_REQUEST",
    GET_DASHBOARDATA_SUCCESS : "GET_DASHBOARDATA_SUCCESS",
    GET_DASHBOARDATA_FAILED : "GET_DASHBOARDATA_FAILED",

    GET_DEMOREQUEST_REQUEST : "GET_DEMOREQUEST_REQUEST",
    GET_DEMOREQUEST_SUCCESS : "GET_DEMOREQUEST_SUCCESS",
    GET_DEMOREQUEST_FAILED : "GET_DEMOREQUEST_FAILED",


}